### ISSUE TITLE
image editing configuration

### ISSUE THREAD

**Issue by SunzeY** [AFeng-x/PixWizard#4]
Thank you for open sourcing such a great work! I'm trying to reproduce image editing results but the results seems not good enough using `inference_pixwizard.sh`. Is there anything different to use this model to do editing task like sampling step and cfg scale?

**Comment by AFeng-x** [comment]
Hi, sorry for the delayed response. Due to the impact of multi-task training, image editing results can sometimes be unstable. You can try running inference with 100 steps, changing the random seed to 42 or using a random value, and increasing the text_cfg_scale value slightly—these adjustments might help. Also, the current model weights are not yet stable and robust enough, but we plan to release better weights after further training.

**Comment by SunzeY** [comment]
thank you for your reply!

**Comment by srvCodes** [comment]
> Hi, sorry for the delayed response. Due to the impact of multi-task training, image editing results can sometimes be unstable. You can try running inference with 100 steps, changing the random seed to 42 or using a random value, and increasing the text_cfg_scale value slightly—these adjustments might help. Also, the current model weights are not yet stable and robust enough, but we plan to release better weights after further training.

Hi, great work and thank you for the open source. Any update on when do you plan to release the more stable weights?
